zonemgr : placeholder for destroy_zone_snapshot()

diff --git a/bin/zonemgr b/bin/zonemgr
--- a/bin/zonemgr
+++ b/bin/zonemgr
@@ -540,8 +540,8 @@ Options: if conflicting options are specified, then the last one wins
     -t|--template NAME  Use this OS-defined template to create a new GIZ
     -b|--brand NAME     Record this brand in the zone attributes
     -c|--clone|--origin NAME    The origin GIZ for cloning into new GIZ or DIZ
-    -s|--snapshot NAME  The snapshot to take from target or use from origin
-            or rollback to on target
+    -s|--snapshot NAME  The snapshot to take from target or use from origin,
+            or rollback to (or destroy-snapshot) on target
     -z|--zone NAME      Target zone to create or otherwise manage
     -Z|--zone-autoname  Generate name for the zone as a hash of requested
             package names. When asked to create-diz or exec-diz,
@@ -681,6 +681,7 @@ TARGET_ZONE=""
 # Which snapshot name will we take of target zone, or clone off origin zone,
 # or rollback to? If empty, then for snapshot this is generated by current
 # timestamp, and for clone/rollback it is the newest snapshot (last in list).
+# TODO: Maybe add parsing of ZONENAME@SNAPNAME syntax into the two variables?
 SNAP_NAME=""
 # TODO: Add a -F to enforce some operations, e.g. rollback (and halt) of a
 # running zone? Or rely on OS tools to fail and so require several operations
@@ -774,6 +775,7 @@ parse_config_args() {
                 esac
                 ;;
             create-giz|create-diz|destroy|snapshot|rollback|pkg-refresh|pkg-upgrade|pkg-install|pkg-uninstall) ACTION="$1" ;;
+            destroy-snapshot|destroy-snap) ACTION=destroy-snapshot ;;
             list|list-giz|list-diz|list-all)
                 [ "$1" = list-all ] && ACTION="list" || ACTION="$1"
                 case "$2" in
@@ -2258,6 +2260,8 @@ rollback_zone() {
     # Check if zoneconfig now differs from one in the snapshot,
     # reapply old config if needed.
     if [ -s "$ZONEROOT_MPT/$ZONENAME.xml" ] ; then
+        # TODO: Port the elevated-privilege exporter from snapshot_zone()
+        # or just use mktemp directory
         $ELEVATE_CMD zoneadm -z "$ZONENAME" detach -n > "$ZONEROOT_MPT/$ZONENAME.xml.new"
         if ! diff "$ZONEROOT_MPT/$ZONENAME.xml" "$ZONEROOT_MPT/$ZONENAME.xml.new" >/dev/null ; then
             logmsg_info "Zone configuration of ${ZONENAME} differs from what we had in the past"
@@ -2270,6 +2274,22 @@ rollback_zone() {
         start_zone "${ZONENAME}"
     fi
     return $SNAP_RES
+}
+
+destroy_zone_snapshot() {
+    local ZONENAME="$1"
+    local SNAPCOMMENT="$2"
+    local D SNAP_RES
+
+    logmsg_info "Destroying snapshot '${SNAPCOMMENT}' of zone '${ZONENAME}'"
+    check_is_managed_zone "$ZONENAME" || return
+
+    TBD
+    # TODO: a simplified variant of destroy_zone() and rollback_zone()
+    # codebase, with purpose to consistently drop intermediate snapshots
+    # of zone-related datasets that are deemed unneeded by an admin user.
+    # Nothing to remount, restart, etc. - though should hiccup on clones
+    # and similar cases that can not be destroyed silently.
 }
 
 # Run a command inside the zone (via zlogin), maybe as a specified account
@@ -2437,7 +2457,16 @@ do_zonemgr() {
             ;;
         destroy)
             check_is_managed_zone "$TARGET_ZONE" || die
-            destroy_zone "$TARGET_ZONE"
+            if [ -n "$SNAP_NAME" ] ; then
+                destroy_zone_snapshot "$TARGET_ZONE" "$SNAP_NAME"
+            else
+                destroy_zone "$TARGET_ZONE"
+            fi
+            ;;
+        destroy-snapshot)
+            check_is_managed_zone "$TARGET_ZONE" || die
+            [ -n "$SNAP_NAME" ] || die "Snapshot name is required for destroy-snapshot"
+            destroy_zone_snapshot "$TARGET_ZONE" "$SNAP_NAME"
             ;;
         snapshot)
             check_is_managed_zone "$TARGET_ZONE" || die
