zonemgr : do_zonemgr() : support an undocumented "$1"=="DEVEL_DEBUG" to invoke functions directly

diff --git a/bin/zonemgr b/bin/zonemgr
--- a/bin/zonemgr
+++ b/bin/zonemgr
@@ -2278,6 +2278,17 @@ do_zonemgr() {
 
     settraps "exit_cleanup"
 
+    if [ "$1" = "DEVEL_DEBUG" ] ; then
+        shift 1
+        logmsg_info "DEBUG-executing a single procedure: $*" >&2
+        ( set -x ; [ $# -gt 0 ] && "$@" )
+        RES_DEBUG=$?
+        if [ "$RES_DEBUG" != 0 ]; then
+            logmsg_error "FAILED with code $RES_DEBUG while running a single procedure: $*" >&2
+        fi
+        exit $RES_DEBUG
+    fi
+
     parse_config_startup "$@"
 
     # CLI args or config files could change the setting
