zonemgr : do not hide non-fatal issues by "|| true" - report them as warnings to reduce surprises

diff --git a/bin/zonemgr b/bin/zonemgr
--- a/bin/zonemgr
+++ b/bin/zonemgr
@@ -28,7 +28,8 @@
 if [ -n "${BASH-}" ]; then
     # A bash-ism, should set the exitcode of the rightmost failed command
     # in a pipeline, otherwise e.g. exitcode("false | true") == 0
-    set -o pipefail 2>/dev/null || true
+    set -o pipefail 2>/dev/null || \
+        echo "WARNING: Could not set up Bash pipefail mode"
     echo_E() { echo -E "$@"; }
     echo_e() { echo -e "$@"; }
 else
@@ -270,7 +271,10 @@ die() {
 
 settraps_exit_clear() {
     # Reset the exit() handler to defaults, used in routines below
-    for SS in EXIT SIGEXIT 0 ERR SIGERR; do trap "-" "$SS" 2>/dev/null || true; done
+    for SS in EXIT SIGEXIT 0 ERR SIGERR; do
+        trap "-" "$SS" 2>/dev/null \
+            || logmsg_warn "Could not reset signal handler for '$SS'"
+    done
     set +E      # unset -o errtrace
 }
 
@@ -300,7 +304,8 @@ settraps_nonfatal() {
             set -o errtrace
         fi
         case "$1" in
-            -|"") trap "$1" "$P$S" 2>/dev/null || true ;;
+            -|"") trap "$1" "$P$S" 2>/dev/null \
+                || logmsg_warn "Could not set up signal handler for '$P$S'" ;;
             *)    ERRHANDLER="$*"
                   case "$ERRHANDLER" in
                     *";"|*"; "|*";  ") ;;
@@ -335,7 +340,8 @@ if [ "${ERRIGNORE-}" = no ]; then
   [ -n "${SCRIPTLIB_DIE_ERRCODE-}" ] && ERRTEXT="${ERRTEXT-}, using die()"
   { (settraps_exit_clear; exit ${ERRCODE-} 2>/dev/null 2>&1); '"$ERRHANDLER"' } ;
 else ERRIGNORE=""; fi ;' \
-                    "$P$S" 2>/dev/null || true
+                    "$P$S" 2>/dev/null \
+                    || logmsg_warn "Could not set up signal handler for '$P$S'"
                   ;;
         esac
     done; done
@@ -373,7 +379,8 @@ settraps() {
     # The ERR* variables reported here are defined by settraps_nonfatal() above
     # Note that all output (if any) goes to stderr (see end of "if" clause).
     case "$1" in
-        -|"") settraps_nonfatal "$1" || true ;;
+        -|"") settraps_nonfatal "$1" \
+            || logmsg_warn "Could not settraps_nonfatal()" ;;
         *)    ERRHANDLER="$*"
               case "$ERRHANDLER" in
                 *";"|*"; "|*";  ") ;;
@@ -428,7 +435,7 @@ fi >&2
 settraps_exit_clear
 { '"$ERRHANDLER"' } || exit $?
 exit ${ERRCODE-};' \
-                || true
+                || logmsg_warn "Could not settraps_nonfatal()"
               ;;
     esac
 }
@@ -682,7 +689,8 @@ parse_config_startup() {
     # Args: pass "$@" of the script
     for F in "/etc/zones/zonemgr.conf" "${HOME}/.zonemgr.conf" ; do
         if [ -s "$F" ] ; then
-            parse_config_file "$F" || true
+            parse_config_file "$F" \
+                || logmsg_warn "Could not use config file '$F'"
         fi
     done
 
@@ -766,16 +774,20 @@ create_dataset_containment_GIZ() {
 
     zfs set -o atime=off "$DATASET_CONTAINMENT_GIZ"
     zfs set -o compression="$DATASET_CONTAINMENT_GIZ_COMPRESSION" "$DATASET_CONTAINMENT_GIZ"
-    zfs set -o com.sun:auto-snapshot=false "$DATASET_CONTAINMENT_GIZ" || true
+    zfs set -o com.sun:auto-snapshot=false "$DATASET_CONTAINMENT_GIZ" || \
+        logmsg_warn "Could not set ZFS props: auto-snapshot on 'DATASET_CONTAINMENT_GIZ'"
     case "$DATASET_CONTAINMENT_GIZ_DEDUP" in
         on|off)
-            zfs set -o dedup="$DATASET_CONTAINMENT_GIZ_DEDUP" "$DATASET_CONTAINMENT_GIZ" || true ;;
+            zfs set -o dedup="$DATASET_CONTAINMENT_GIZ_DEDUP" "$DATASET_CONTAINMENT_GIZ" || \
+                logmsg_warn "Could not set ZFS props: dedup on 'DATASET_CONTAINMENT_GIZ'" ;;
     esac
     if [ -n "$DATASET_CONTAINMENT_GIZ_MPT" ]; then
-        zfs set -o mountpoint="$DATASET_CONTAINMENT_GIZ_MPT" "$DATASET_CONTAINMENT_GIZ" || true
+        zfs set -o mountpoint="$DATASET_CONTAINMENT_GIZ_MPT" "$DATASET_CONTAINMENT_GIZ" || \
+            logmsg_warn "Could not set ZFS props: mountpoint on 'DATASET_CONTAINMENT_GIZ'"
     fi
     zfs set -o canmount=auto "$DATASET_CONTAINMENT_GIZ"
-    zfs mount "$DATASET_CONTAINMENT_GIZ" || true
+    zfs mount "$DATASET_CONTAINMENT_GIZ" || \
+        logmsg_warn "Could not mount ZFS dataset: 'DATASET_CONTAINMENT_GIZ'"
 }
 
 create_dataset_containment_DIZ() {
@@ -794,13 +806,17 @@ create_dataset_containment_DIZ() {
 
     zfs set -o atime=off "$DATASET_CONTAINMENT_DIZ"
     zfs set -o compression="$DATASET_CONTAINMENT_DIZ_COMPRESSION" "$DATASET_CONTAINMENT_DIZ"
-    zfs set -o com.sun:auto-snapshot=false "$DATASET_CONTAINMENT_DIZ" || true
-    zfs set -o dedup=off "$DATASET_CONTAINMENT_DIZ" || true
+    zfs set -o com.sun:auto-snapshot=false "$DATASET_CONTAINMENT_DIZ" || \
+        logmsg_warn "Could not set ZFS props: auto-snapshot on 'DATASET_CONTAINMENT_DIZ'"
+    zfs set -o dedup=off "$DATASET_CONTAINMENT_DIZ" || \
+        logmsg_warn "Could not set ZFS props: dedup on 'DATASET_CONTAINMENT_DIZ'"
     if [ -n "$DATASET_CONTAINMENT_DIZ_MPT" ]; then
-        zfs set -o mountpoint="$DATASET_CONTAINMENT_DIZ_MPT" "$DATASET_CONTAINMENT_DIZ" || true
+        zfs set -o mountpoint="$DATASET_CONTAINMENT_DIZ_MPT" "$DATASET_CONTAINMENT_DIZ" || \
+            logmsg_warn "Could not set ZFS props: mountpoint on 'DATASET_CONTAINMENT_DIZ'"
     fi
     zfs set -o canmount=auto "$DATASET_CONTAINMENT_DIZ"
-    zfs mount "$DATASET_CONTAINMENT_DIZ" || true
+    zfs mount "$DATASET_CONTAINMENT_DIZ" || \
+        logmsg_warn "Could not mount ZFS dataset: 'DATASET_CONTAINMENT_DIZ'"
 }
 
 ############################################################################
