zonemgr : clean up confusion of ORIGIN_ZONE, use ORIGIN_GIZ anywhere concerned

diff --git a/bin/zonemgr b/bin/zonemgr
--- a/bin/zonemgr
+++ b/bin/zonemgr
@@ -702,10 +702,6 @@ TEMPLATE_GIZ="SUNWipkg"
 BRAND_GIZ="ipkg"
 # Which golden-image zone the target one (GIZ or DIZ) is cloned from
 ORIGIN_GIZ=""
-# Generally, code supports cloning of anything to anything - this value is
-# not supposed to be set directly, and is set to $ORIGIN_GIZ (if available)
-# or generated during clone_zone()
-ORIGIN_ZONE=""
 # Which zone will we manage with this command?
 TARGET_ZONE=""
 # Which snapshot name will we take of target zone, or clone off origin zone,
@@ -1917,8 +1913,8 @@ setup_zone_name() {
 
     $ELEVATE_CMD zlogin -S "${ZONENAME}" << EOF
 echo "${ZONEHOSTNAME}" > "/etc/nodename"
-if [ -n "${ORIGIN_ZONE}" ] ; then
-    sed -e 's,^\(127\.0\.0\.1.*[\ \t]\)'"${ORIGIN_ZONE}"'\([\ \t].*|\)$,\1\2,' \
+if [ -n "${ORIGIN_GIZ}" ] ; then
+    sed -e 's,^\(127\.0\.0\.1.*[\ \t]\)'"${ORIGIN_GIZ}"'\([\ \t].*|\)$,\1\2,' \
         -i /etc/hosts
 fi
     sed -e 's,^\(127\.0\.0\.1.*[\ \t].*\)$,\1\t'"${ZONEHOSTNAME}"',' \
@@ -2283,25 +2279,21 @@ clone_zone() {
         # TBD: forcing or re-creation is not supported by the script... should it be?
     fi
 
-    # If ORIGIN_ZONE is not set or is missing, install it first and
+    # If ORIGIN_GIZ is not set or is missing, install it first and
     # then clone it here - so we can later quickly spawn same setups
-    if [ -z "$ORIGIN_ZONE" ]; then
-        if [ -n "$ORIGIN_GIZ" ]; then
-            ORIGIN_ZONE="$ORIGIN_GIZ"
-        else
-            ORIGIN_ZONE="$(generate_zonename)"
-            logmsg_warn "An ORIGIN_ZONE name was not provided, generated '$ORIGIN_ZONE'"
-        fi
+    if [ -z "$ORIGIN_GIZ" ]; then
+        ORIGIN_GIZ="$(generate_zonename)"
+        logmsg_warn "An ORIGIN_GIZ name was not provided, generated '$ORIGIN_GIZ'"
     fi
 
-    if ! check_is_managed_zone "$ORIGIN_ZONE" ; then
+    if ! check_is_managed_zone "$ORIGIN_GIZ" ; then
         # TBD: Here we check if a zone by this name is not installed at all
         # and do not look at the type (GIZ/DIZ). Not sure yet if this is a
         # desirable behavior (should we let clone DIZ if asked explicitly)?
-        logmsg_info "An ORIGIN_ZONE='$ORIGIN_ZONE' was not installed," \
+        logmsg_info "An ORIGIN_GIZ='$ORIGIN_GIZ' was not installed," \
             "preparing it as a GIZ to clone later into TARGET_ZONE='$TARGET_ZONE' DIZ"
-        ( TARGET_ZONE="$ORIGIN_ZONE" ; install_zone ) \
-            || die "FAILED to install an ORIGIN_ZONE='$ORIGIN_ZONE'"
+        ( TARGET_ZONE="$ORIGIN_GIZ" ; install_zone ) \
+            || die "FAILED to install an ORIGIN_GIZ='$ORIGIN_GIZ'"
     fi
 
     TBD
